//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Encuesta
    {
        public int idEncuesta { get; set; }
        public int idPerformance { get; set; }
        public int recibido { get; set; }
        public int calidad { get; set; }
        public string comentario { get; set; }
    }
}
