//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EvaluacionPerformance
    {
        public int idEvaluacion { get; set; }
        public int idPerformance { get; set; }
        public Nullable<int> idHabilidad { get; set; }
        public Nullable<int> idCalificacion { get; set; }
        public System.DateTime fechaEvaluacion { get; set; }
        public Nullable<int> idResponsable { get; set; }
    }
}
