//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GralUsuario
    {
        public int idUsuario { get; set; }
        public string Nombre { get; set; }
        public string dni { get; set; }
        public string email { get; set; }
        public Nullable<int> idSubOficina { get; set; }
        public Nullable<int> idOficina { get; set; }
        public string password { get; set; }
        public Nullable<int> idPerfil { get; set; }
        public string usuario { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<System.DateTime> ultimoLogin { get; set; }
        public Nullable<int> codBizagi { get; set; }
        public Nullable<int> legajo { get; set; }
        public Nullable<int> nroSAP { get; set; }
        public Nullable<int> idReloj { get; set; }
        public Nullable<System.TimeSpan> entrada { get; set; }
        public Nullable<System.TimeSpan> salida { get; set; }
        public string sede { get; set; }
        public string comedor { get; set; }
        public Nullable<int> cantidadHoras { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<int> idReloj2 { get; set; }
        public string nombreUsuario { get; set; }
        public string apellidoUsuario { get; set; }
        public Nullable<int> idSede { get; set; }
        public string foto { get; set; }
        public Nullable<bool> marca { get; set; }
        public Nullable<int> idUsuarioInternet { get; set; }
        public Nullable<System.DateTime> fechaBaja { get; set; }
        public Nullable<int> idJefe { get; set; }
        public string tratamiento { get; set; }
        public string sexo { get; set; }
        public Nullable<int> categoria { get; set; }
        public string cuil { get; set; }
        public Nullable<int> tieneComedor { get; set; }
        public Nullable<int> compensa { get; set; }
        public Nullable<int> horaExtra { get; set; }
        public Nullable<int> idConvenio { get; set; }
        public Nullable<int> trabajaFinDe { get; set; }
        public Nullable<bool> esCtr { get; set; }
        public string centroCosto { get; set; }
        public Nullable<bool> diferenciaSAP { get; set; }
        public Nullable<bool> esGuardia { get; set; }
        public Nullable<bool> tieneHoraAlmuerzo { get; set; }
        public string pais { get; set; }
        public Nullable<int> horaExtraObra { get; set; }
        public Nullable<int> bonoDispo { get; set; }
        public Nullable<int> IdProvincia { get; set; }
        public Nullable<int> idSeniority { get; set; }
        public Nullable<int> tipoGuardia { get; set; }
        public Nullable<int> idJefeVia { get; set; }
        public Nullable<bool> tieneCumpleanos { get; set; }
        public Nullable<bool> esPerformance { get; set; }
        public Nullable<int> idDominio { get; set; }
    }
}
