//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Historial
    {
        public int idHistorial { get; set; }
        public int idPerformance { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<int> idUsuarioCambio { get; set; }
        public Nullable<int> idHabilidad { get; set; }
        public Nullable<int> idCalificacion { get; set; }
        public Nullable<int> idCalificacionFinal { get; set; }
        public Nullable<int> idResponsableOriginal { get; set; }
        public Nullable<System.DateTime> fechaOriginal { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public Nullable<bool> autoevaluacion { get; set; }
        public Nullable<bool> evaluacion { get; set; }
        public Nullable<bool> calibracion { get; set; }
        public System.DateTime fechaCambio { get; set; }
        public string nombreUsuarioCambio { get; set; }
        public Nullable<int> idCalificacionFinalAntes { get; set; }
    }
}
