//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PerformanceEntities : DbContext
    {
        public PerformanceEntities()
            : base("name=PerformanceEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AutoEvaluacion> AutoEvaluacion { get; set; }
        public virtual DbSet<Calificacion> Calificacion { get; set; }
        public virtual DbSet<CalificacionFinalLider> CalificacionFinalLider { get; set; }
        public virtual DbSet<Encuesta> Encuesta { get; set; }
        public virtual DbSet<Estados> Estados { get; set; }
        public virtual DbSet<EstadosFechas> EstadosFechas { get; set; }
        public virtual DbSet<EvaluacionPerformance> EvaluacionPerformance { get; set; }
        public virtual DbSet<Historial> Historial { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<MenuPerfil> MenuPerfil { get; set; }
        public virtual DbSet<PDIColaborador> PDIColaborador { get; set; }
        public virtual DbSet<PDIStatus> PDIStatus { get; set; }
        public virtual DbSet<PDItipoAccion> PDItipoAccion { get; set; }
        public virtual DbSet<PerformanceColaborador> PerformanceColaborador { get; set; }
        public virtual DbSet<Habilidades> Habilidades { get; set; }
        public virtual DbSet<PDIColaboradorMetas> PDIColaboradorMetas { get; set; }
    }
}
