//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BuhoGestionEntities : DbContext
    {
        public BuhoGestionEntities()
            : base("name=BuhoGestionEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GralDominio> GralDominio { get; set; }
        public virtual DbSet<GralUsuario> GralUsuario { get; set; }
        public virtual DbSet<RecConvenio> RecConvenio { get; set; }
        public virtual DbSet<SegUsuarioPerfil> SegUsuarioPerfil { get; set; }
        public virtual DbSet<UocCategoria> UocCategoria { get; set; }
    }
}
