//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDIColaboradorMetas
    {
        public int idMeta { get; set; }
        public Nullable<int> idPDI { get; set; }
        public Nullable<int> tipoAccion { get; set; }
        public Nullable<int> habilidad { get; set; }
        public string metaTitulo { get; set; }
        public string metaDescripcion { get; set; }
        public Nullable<System.DateTime> fechaDesde { get; set; }
        public Nullable<System.DateTime> fechaHasta { get; set; }
        public Nullable<int> status { get; set; }
        public string accionesRealizadas { get; set; }
    }
}
