//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PerformanceColaborador
    {
        public int idPerformance { get; set; }
        public int idUsuario { get; set; }
        public Nullable<int> legajo { get; set; }
        public string nombre { get; set; }
        public Nullable<int> edad { get; set; }
        public string sexo { get; set; }
        public int antiguedad { get; set; }
        public string pais { get; set; }
        public string convenio { get; set; }
        public string dominio { get; set; }
        public string categoria { get; set; }
        public int idJefe { get; set; }
        public string nombreJefe { get; set; }
        public int ano { get; set; }
        public Nullable<int> estado { get; set; }
        public Nullable<System.DateTime> fechaAutoevaluacion { get; set; }
        public Nullable<System.DateTime> fechaEvaluacion { get; set; }
        public Nullable<System.DateTime> fechaCalibracion { get; set; }
        public string calificacionFinal { get; set; }
        public Nullable<int> idCalificacionFinal { get; set; }
        public Nullable<bool> eliminado { get; set; }
        public string comentario { get; set; }
        public Nullable<int> idCalificacionFinalAntes { get; set; }
        public string calificacionFinalAntes { get; set; }
    }
}
