//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Performance.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecConvenio
    {
        public int idConvenio { get; set; }
        public string nombreConvenio { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
